name: Security

on:
  pull_request:
    branches: [main]

jobs:
  secret-detection:
    uses: Danih96/standardized-security/.github/workflows/secret-detection.yml@main

  dependency-scanning:
    uses: Danih96/standardized-security/.github/workflows/dependency-scanning.yml@main
